// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Handlers} from "./handlers/Handlers.sol";
import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    function setUp() public {
        setup();
    }

    // forge test --match-test test_sequence -vvv
    function test_sequence() public {
        // Add here call sequence to Handler's functions to reproduce failing property
    }

    function test_exclusivePaidCapPropertyAllowsFractionalOverhang() public {
        vm.prank(creator);
        fixedTier.setMaxPrepaidPeriods(1);
        membershipTier_createMembership(1, address(0), 64);
        vm.warp(block.timestamp + 1);
        fixedTier.processAccounting(64);
        membershipTier_probeRenewalExactness(false, 0, 0);
        (uint64 paid,,) = fixedTier.timeBalances(1);
        assertEq(paid, 2 * fixedTier.periodDuration() - 1);
    }

    function test_refillPurchaseAndRetentionPreviewProperties() public {
        membershipTier_createMembership(1, address(0), 64);
        membershipTier_setRefillTarget_clamped(0, 2 * fixedTier.periodDuration() - 1);
        uint256 gross = fixedTier.lifetimeGross();
        membershipTier_refill_clamped(0, 0, 63);
        assertEq(fixedTier.lifetimeGross(), gross + fixedTier.pricePerPeriod());
        assertEq(fixedTier.creatorRetentionBps(), 3000);
        membershipTier_refundFromPreview(false, 0);
        assertEq(fixedTier.totalSupply(), 0);
        property_accountingConservation();
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────
    // Each test_repro_* function below replays a shrunk fuzzer call
    // sequence that violated a property. Run all with:
    //   forge test --match-contract FoundryTester -vvv
}
